name: GitBeek
options:
  bundleIdPrefix: com.gitbeek
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  developmentLanguage: en
  defaultConfig: Debug
  groupSortPosition: top
  generateEmptyDirectories: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_FILE: GitBeek/Resources/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: true
    SWIFT_EMIT_LOC_STRINGS: true
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: "5.9.0"
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: "3.0.0"
  swift-markdown:
    url: https://github.com/apple/swift-markdown
    from: "0.4.0"
  Splash:
    url: https://github.com/JohnSundell/Splash
    from: "0.16.0"
  swift-dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.0.0"

targets:
  GitBeek:
    type: application
    platform: iOS
    sources:
      - path: GitBeek
        excludes:
          - "**/.DS_Store"
    resources:
      - path: GitBeek/Resources/Assets.xcassets
      - path: GitBeek/Resources/Info.plist
        buildPhase: none
    dependencies:
      - package: Alamofire
      - package: SDWebImageSwiftUI
      - package: swift-markdown
        product: Markdown
      - package: Splash
      - package: swift-dependencies
        product: Dependencies
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gitbeek.app
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    preBuildScripts: []
    postBuildScripts: []

  GitBeekTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GitBeekTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: GitBeek
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gitbeek.app.tests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/GitBeek.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/GitBeek"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  GitBeek:
    build:
      targets:
        GitBeek: all
        GitBeekTests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-UIPreferredContentSizeCategoryName": "UICTContentSizeCategoryL"
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - GitBeek
      targets:
        - GitBeekTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
